<?
class main{
	private $data=array();
	
	public function __set($name, $value){
		$this->data[$name] = $value;
	}
	
	public function __get($name){
		return $this->data[$name];
	}

	public function __isset($name) {
        return isset($this->data[$name]);
    }
	
	public function __unset($name) {
        unset($this->data[$name]);
    }

/* ############################# metode umum ########################################*/

	public static function date_database_formatting($arr_month, $date){
		$arr_date=preg_split("/ /", $date);
		$month = main::get_array_index($arr_month, $arr_date[1], "value")+1;
		$month = $month < 10 ? "0" . $month : $month;
		return $arr_date[2]."-".$month."-".$arr_date[0];
	}
	
	public static function date_from_jquery_to_string($arr_month, $date){
		$arr_date=explode("/", $date);
		return $arr_date[0]." ".$arr_month[(int)$arr_date[1] - 1]." ".$arr_date[2];		
	}
	
	public static function formatting_query_string($string){
		$string=str_replace("'", "\'", $string);// amankan karakter ' :database
		$string=str_replace("<", "&lt;", $string);// amankan karakter-2 berpotensi xss
		$string=str_replace(">", "&gt;", $string);
		$string=str_replace("&lt;br /&gt;", "<br />", $string);//pulihkan hanya untuk html break
		$string=str_replace("&lt;strong&gt;", "<strong>", $string);$string=str_replace("&lt;/strong&gt;", "</strong>", $string);//pulihkan hanya untuk html strong
		$string=str_replace("&lt;hr width=100% size=1 /&gt;", "<hr width=100% size=1 />", $string);//pulihkan hanya untuk html horizontal line
		//$string=str_replace("=", "&#61;", $string);
		//$string=str_replace("\"", "&quot;", $string);		
		return $string;
	}
	
	public static function formatting_javascript_string($string){
		$string=str_replace("'", "\\'", $string);// amankan karakter ' :javascript
		$string=str_replace("<", "&lt;", $string);// amankan karakter-2 berpotensi xss
		$string=str_replace(">", "&gt;", $string);
		$string=str_replace("&lt;br /&gt;", "<br />", $string);//pulihkan hanya untuk html break
		$string=str_replace("&lt;strong&gt;", "<strong>", $string);$string=str_replace("&lt;/strong&gt;", "</strong>", $string);//pulihkan hanya untuk html strong
		$string=str_replace("&lt;hr width=100% size=1 /&gt;", "<hr width=100% size=1 />", $string);//pulihkan hanya untuk html horizontal line
		//$string=str_replace("=", "&#61;", $string);
		//$string=str_replace("\"", "&quot;", $string);		
		return $string;	
	}
	
	public static function formatting_output_html_string($string){
		$string = str_ireplace("<br />", "\r\n", $string); 
		return $string;
	}
	
	static function __set_option($arr, $opt_selected="", $mode=""){
		$s_option="";
		foreach($arr as $key=>$value){
			$selected="";
			if(!is_array($value)){
				if($mode=="")	{if($opt_selected==$key)$selected="selected";}
				else{if($opt_selected==$value)$selected="selected";}
				if($mode=="")	$s_option.="<option value=\"".$key."\" ".$selected.">".ucwords(strtolower($value))."</option>";
				else $s_option.="<option value=\"".$value."\"".$selected.">".ucwords(strtolower($value))."</option>";
			}else{				
				foreach($value as $key1=>$value1){
					$selected="";
					if($mode=="")	{if($opt_selected==$key1)$selected="selected";}
					else{if($opt_selected==$value1)$selected="selected";}
					
					if($mode=="")	$s_option.="<option value=\"".$key1."\" ".$selected.">".ucwords(strtolower($value1))."</option>";
					else $s_option.="<option value=\"".$value1."\"".$selected.">".ucwords(strtolower($value1))."</option>";
				}
			}
		}
		return $s_option;
	}
	
	public static function reload_page($arr_request,$url="", $target="_self"){
		echo "<html><body onload=\"javascript:form1.submit()\">";
		echo "<form name=\"form1\" id=\"form1\" method=\"post\" action=\"".$url."\" target=\"". $target ."\">";
		foreach($arr_request as $key=>$value)
			echo "<input type=\"hidden\" name=\"".$key."\" id=\"".$key."\" value=\"".$value."\" />";
		echo "</form>";
		echo "</body></html>";
	}

/* ajax */	
	static function __callback(
		$callback = "", 
		$msg = "", 
		$is_direct = false /*false : diparsing dulu ke js function generated by fungsi dibawah, sblm ditampilin ke user; true : langsung ditampilin ke user*/
	){
		if(!$is_direct){
			if($callback == "") throw new Exception('js callback function not set!');
			$tinybox = "TINY.box.show({image:'". __DIR__ ."/../images/loading.gif',boxid:'',width:33,height:33,fixed:true,maskid:'greymask',maskopacity:40,close:false});";
			$return = "<script>try{window.onload=function(){". $tinybox . $callback .";callback('". $msg ."');}}catch(err){alert(err)}</script>";
		}else	$return = $msg;
		return $return;
	}
	
	static function initiating_callback($obj, $msg){
		$cb = "callback";
		if(@$_REQUEST[$cb] != ""){						
			$obj->view->assign($cb, self::__callback($_REQUEST[$cb], $msg));
			$obj->view->display('loading_view');
		}else	echo self::__callback("", $msg, true);
	}
	
// ##############################################################################################



/*
fungsi send email error
*/
	public static function send_email($target=SUPPORT_EMAIL,$subject="",$content="", $lampiran=array()){
		$message=file_get_contents(EMAIL_TEMPLATE);	

		$message=str_replace("#greetingname#", $target, $message);
		$message=str_replace("#content#", $content, $message);
		$message=str_replace("#lang_email_info_en#", "", $message);
		$message=str_replace("#lang_email_footer#", "", $message);
		$message=str_replace("#horizontal_line#", "<hr width=100% size=1 />", $message);

		if($target=="")$target=SUPPORT_EMAIL;
		$subject = $subject;
		$to["To"]=$target;
		$to["Bcc"]=SUPPORT_EMAIL;
		$recipient_header_to=$target;
		$from=SUPPORT_EMAIL;

		ini_set("include_path",INCLUDE_PATH);
		require_once "pear/Mail.php";
		require_once "pear/mime.php";		
		
		$mime=new Mail_mime(array('eol' => CRLF));
		$mime->setTXTBody(strip_tags($message));
		$mime->setHTMLBody($message);	
		if(count($lampiran)>0)
			foreach($lampiran as $key)$mime->addAttachment($key);
		
		$headers = array ('From' => $from,
			'To' => $recipient_header_to, 
			'Subject' => $subject);		
		$smtp=Mail::factory('smtp',
			array ('host' => SMTP_HOST,
			'auth' => SMTP_AUTH,
			'username' => SMTP_USERNAME,
			'password' => SMTP_PASSWORD));		
						
		$body=$mime->get();
		$headers_=$mime->headers($headers);		

		if( EMAIL_DIAKTIFKAN )
			$mail = $smtp->send($to, $headers_, $body);
		
		$pear=new PEAR;
		if ($pear->isError($mail))echo "Email Error. " . $mail->getMessage();
		restore_include_path ();
		//mail($to, $subject, $message, $headers);		
		//return $message;
	}
	
	
}
?>